# placeholders for clippy and other tools
# Program IDs may not be correct
[env]
TIP_ROUTER_PROGRAM_ID = "GTqZwAJV9UpqhaisrTbR2V6D8AUSWcTWyH9JEsaJEsEZ"
RESTAKING_PROGRAM_ID = "RestkWeAVL8fRGgzhfeoqFhsqKRchg6aa1XrcH96z4Q"
VAULT_PROGRAM_ID = "Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"
